name: Build and Push Docker Image
description: Builds a Docker image and pushes it to either Amazon ECR or Harbor

inputs:
  platform:
    description: 'Platform to build for (e.g., linux/amd64 or linux/arm64)'
    required: true
  image-tag:
    description: 'Image tag to use (e.g., dev-123)'
    required: true
  github-sha:
    description: 'GitHub commit SHA'
    required: true
  ecr-registry:
    description: 'ECR registry URL. Provide this OR harbor-registry, not both.'
    required: false
    default: ''
  harbor-registry:
    description: 'Harbor registry URL (e.g., harbor.bisnow.cloud/bisnow/hello-k8s). Provide this OR ecr-registry, not both.'
    required: false
    default: ''
  aws-account:
    description: 'AWS account name to assume role for'
    required: false
    default: 'bisnow'
  auth-json:
    description: 'Create auth-json for composer auth and/or flux auth'
    required: false
    default: ''
  composer-auth:
    description: 'Composer authentication token for GitHub'
    required: false
  flux-username:
    description: 'Flux UI username for http-basic authentication'
    required: false
  flux-license-key:
    description: 'Flux UI license key for http-basic authentication'
    required: false
  php-version:
    description: 'PHP version to set up'
    required: false
    default: '8.3'
  install-dependencies:
    description: 'Install composer dependencies in workflow'
    required: false
    default: ''
  no-cache:
    description: 'Build without using cache (slower but ensures fresh build)'
    required: false
    type: boolean
    default: false
  build-args:
    description: 'Build args to pass to docker build'
    required: false
  build-assets:
    description: 'Build assets'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Validate registry inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.ecr-registry }}" ] && [ -z "${{ inputs.harbor-registry }}" ]; then
          echo "ERROR: You must provide either ecr-registry or harbor-registry"
          exit 1
        fi
        if [ -n "${{ inputs.ecr-registry }}" ] && [ -n "${{ inputs.harbor-registry }}" ]; then
          echo "ERROR: Provide ecr-registry OR harbor-registry, not both"
          exit 1
        fi

    - name: Set active registry
      id: registry
      shell: bash
      run: |
        if [ -n "${{ inputs.harbor-registry }}" ]; then
          echo "url=${{ inputs.harbor-registry }}" >> $GITHUB_OUTPUT
        else
          echo "url=${{ inputs.ecr-registry }}" >> $GITHUB_OUTPUT
        fi

    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Use Node.js
      if: ${{ inputs.build-assets != '' }}
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Build Assets
      if: ${{ inputs.build-assets != '' }}
      shell: bash
      run: |
        npm ci
        npm run build

    - name: Set up PHP
      if: ${{ inputs.auth-json != '' && (inputs.composer-auth != '' || (inputs.flux-username != '' && inputs.flux-license-key != '')) }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        tools: composer:v2

    - name: Configure Composer credentials
      if: ${{ inputs.auth-json != '' && (inputs.composer-auth != '' || (inputs.flux-username != '' && inputs.flux-license-key != '')) }}
      shell: bash
      run: |
        if [ -n "${{ inputs.composer-auth }}" ]; then
          composer config github-oauth.github.com "${{ inputs.composer-auth }}"
        fi
        if [ -n "${{ inputs.flux-username }}" ] && [ -n "${{ inputs.flux-license-key }}" ]; then
          composer config http-basic.composer.fluxui.dev "${{ inputs.flux-username }}" "${{ inputs.flux-license-key }}"
        fi

    - name: Assume role for AWS Account
      uses: bisnow/github-actions-assume-role-for-environment@main
      with:
        aws-account: ${{ inputs.aws-account }}

    - name: Install dependencies
      if: ${{ inputs.install-dependencies != '' }}
      uses: php-actions/composer@v6
      env:
        COMPOSER_AUTH: "{\"github-oauth\":{\"github.com\":\"${{ inputs.composer-auth }}\"}}"
      with:
        args: --no-dev --profile --ignore-platform-reqs --optimize-autoloader
        memory_limit: -1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push ${{ inputs.platform }} Image (${{ inputs.image-tag }})
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: ${{ inputs.platform }}
        push: true
        no-cache: "${{ inputs.no-cache || false }}"
        tags: |
          ${{ steps.registry.outputs.url }}:${{ inputs.image-tag }}-${{ inputs.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
          ${{ steps.registry.outputs.url }}:${{ inputs.github-sha }}-${{ inputs.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
        cache-from: type=registry,ref=${{ steps.registry.outputs.url }}:cache-${{ inputs.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
        cache-to: type=registry,ref=${{ steps.registry.outputs.url }}:cache-${{ inputs.platform == 'linux/amd64' && 'amd64' || 'arm64' }},mode=max
        build-args: ${{ inputs.build-args }}
        provenance: false
        sbom: false
        secret-files: ${{ inputs.auth-json != '' && 'composer_auth=auth.json' || '' }}
