name: Build and Push Docker Image to ECR
description: Builds a Docker image and pushes it to Amazon ECR

inputs:
  aws-account:
    description: 'AWS account name to assume role for'
    required: true
  platform:
    description: 'Platform to build for (e.g., linux/amd64 or linux/arm64)'
    required: true
  image-tag:
    description: 'Image tag to use (e.g., dev-123)'
    required: true
  ecr-registry:
    description: 'ECR registry URL'
    required: true
  github-sha:
    description: 'GitHub commit SHA'
    required: true
  composer-auth:
    description: 'Composer authentication token for GitHub'
    required: false
  install-dependencies:
    description: 'Install composer dependencies in workflow'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Assume role for AWS Account
      uses: bisnow/github-actions-assume-role-for-environment@main
      with:
        aws-account: ${{ inputs.aws-account }}

    - name: Install dependencies
      if: ${{ inputs.install-dependencies != '' }}
      uses: php-actions/composer@v6
      env:
        COMPOSER_AUTH: "{\"github-oauth\":{\"github.com\":\"${{ inputs.composer-auth }}\"}}"
      with:
        args: --profile --ignore-platform-reqs --optimize-autoloader
        memory_limit: -1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push ${{ inputs.platform }} Image to ECR (${{ inputs.image-tag }})
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: ${{ inputs.platform }}
        push: true
        tags: |
          ${{ inputs.ecr-registry }}:${{ inputs.image-tag }}-${{ inputs.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
          ${{ inputs.ecr-registry }}:${{ inputs.github-sha }}-${{ inputs.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
        cache-from: type=registry,ref=${{ inputs.ecr-registry }}:cache-${{ inputs.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
        cache-to: type=registry,ref=${{ inputs.ecr-registry }}:cache-${{ inputs.platform == 'linux/amd64' && 'amd64' || 'arm64' }},mode=max
        build-args: ${{ inputs.install-dependencies == '' && inputs.composer-auth != '' && format('COMPOSER_AUTH={{"github-oauth":{{"github.com":"{0}"}}}}', inputs.composer-auth) || '' }}
        provenance: false
        sbom: false
